name: Conda Constructor Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conda Constructor
        run: pip install constructor 

      - name: change directory
        run: cd constructor

      - name: Build Conda installer
        run: constructor .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: conda-installer-${{ matrix.os }}
          path: installer/
