name: Conda Constructor Build (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: myenv

      - name: Bash
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Create Conda environment
        run: conda create --name myenv python=3.9

      - name: Activate Conda environment
        run: conda activate myenv

      - name: Install Conda Constructor
        run: conda install constructor -y

      - name: change directory
        run: cd constructor

      - name: Build Conda installer
        run: constructor .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: conda-installer-${{ matrix.os }}
          path: installer/
